### ISSUE TITLE
Regarding "$" sign in EN files.

### ISSUE THREAD

**Issue by tinnan** [Treeofsavior/ThaiTranslation#26]
From English translation project's guideline (See https://github.com/Treeofsavior/EnglishTranslation/wiki/Guidelines)
"No.8. Add an "$" Mark in front of the translation For Edited / Reviewed so others would not repeat the same lines."

So, the "$" 's at the start of any translation lines in the EN files are just an Edited / Reviewed indicator marked by English translators. 
Should we keep them or remove them when translate to Thai?

**Comment by zenasis** [comment]
Hello,

Of course, It's just kind of suggestion to avoid duplicated works among our
contributors.

Thanks. :D

2015-12-11 2:32 GMT+09:00 tinnan notifications@github.com:

**Comment by tinnan** [comment]
Well, I think I will just leave them as they are then.
