### ISSUE TITLE
The space between translated text and code should be separate with 1 tab or 1 spacebar ?

### ISSUE THREAD

**Issue by Sweetez** [Treeofsavior/ThaiTranslation#8]
title

**Comment by ghost** [comment]
I go with 1 spacebar.I don't know it's right or wrong tho.
updated:I think its 1 tab.

**Comment by Pearseak** [comment]
also note that some IDE and text editors convert tab to 4 spaces

**Comment by zerosistem** [comment]
I copy from Eng version
it's 3 space -..-"

**Comment by ghost** [comment]
If I do the translate on the website.It'll use only 1 space bar.but If i copy to another program such as Note++.It'll turn in to 1 tab.My bad :P

**Comment by Ceece** [comment]
TSV is tab-separated values. It should be tab, Am I right ?
https://en.wikipedia.org/wiki/Tab-separated_values

**Comment by HalfEmptyChair** [comment]
What if I cannot use Tab button?
FYI, I'm typing using my smart phone. Got no PC or labtop at my workplace, you see. _sniff_

**Comment by Ceece** [comment]
Try to open it with with excel

**Comment by Sweetez** [comment]
@Ceece MS Excel is expensive tbh. I'll just use Libre Office then.
